### ISSUE TITLE
Absolute_time alignment error

### ISSUE THREAD

**Issue by ZhixiaoSu** [AllenNeuralDynamics/aind-dynamic-foraging-data-utils#49]
**Describe the bug**
Absolute time in the dataframe was supposed to be aligned to go cue of first trial, but is now aligned to the start of the first trial. In behavior control, a trial starts with and ITI, followed by a no lick window and then go cue comes. 

**To Reproduce**
Please check this line: 
https://github.com/AllenNeuralDynamics/aind-dynamic-foraging-data-utils/blob/main/src/aind_dynamic_foraging_data_utils/nwb_utils.py#L332

**Expected behavior**
Time is aligned to first go cue.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: codeocean, ubuntu
 - Browser: chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alexpiet** [comment]
Oof! good catch. This is probably my fault. Lets double check to make sure we are aligning everything to the start of the first go cue, and not the start of the first trial (FIP, events, trials table)

**Comment by rachelstephlee** [comment]
I've tracked the line that got messed up: 

```
    t0 = df_ses_trials.start_time[0]
    absolute_time = df_ses_trials['goCue_start_time'] - t0

```

**Comment by rachelstephlee** [comment]
closed with https://github.com/AllenNeuralDynamics/aind-dynamic-foraging-data-utils/pull/50
